name: gh-pages deployment

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  ghpages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install nmrium and create toc
        run: |
          npm i nmrium-cli --global
          npx nmrium toc -c --nostructure
          git status
          git remote -v
      - name: push to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: .
